Fixed issue with missing argument in MNIST example (#520)
Summary:
Pull Request resolved: https://github.com/pytorch/opacus/pull/520

sr stands for sampling rate, which is now legacy code. Now, it's just sample_rate = 1 / len(data_loader). This has been fixed in the example, by setting batch size to be 60000 * 0.004 = 240 (thanks to https://github.com/ffuuugor for the clarification).

On another note, when running with DP, the following error is thrown
```
AttributeError: Can't pickle local object 'wrap_collate_with_empty.<locals>.collate'
```

For now, a temporary fix (based on https://github.com/IBM/Project_CodeNet/issues/21#issuecomment-864619383) is to make num_workers=0 in the dataset loaders. This commit does that.

Reviewed By: ffuuugor

Differential Revision: D40253037

fbshipit-source-id: 99984f8963a4efea6829d109bb81acff0e587c93