Remove pip freeze from PyPI release process
Summary:
tl;dr: you can't install `opacus==0.10.0` (latest version) with `pip install` on python3.7+

## Issue
```
> python --version
Python 3.7.7
> pip install opacus
...
ERROR: Could not find a version that satisfies the requirement dataclasses==0.7 (from opacus) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.7 (from opacus)
```
That said, installing from github checkout works fine:
```
> cd opacus-0.10.0/
> python setup.py install
...
OK
```

Dataclasses were first introduced in python3.7. `dataclasses` package is a backport of the feature for python3.6.
Most importantly, starting [version 0.7](https://pypi.org/project/dataclasses/) it has a strict requirement on python version, prohibiting installation on 3.7+:
```
> pip install dataclasses==0.7
ERROR: Package 'dataclasses' requires a different Python: 3.7.7 not in '>=3.6, <3.7'
```

Now, why do we require it?
Short answer - we don't. It's not listed as opacus requirement neither in requirements.txt not in setup.py.

What happens is:
1) `dataclasses` is a dependency for `torch`, conditional on python version.
[pytorch/setup.py](https://github.com/pytorch/pytorch/blob/master/setup.py): `dataclasses; python_version < "3.7"`

2) Apparently, env where we build package does have python3.6
3) As the last step in our installation process we override requirements.txt by doing
```
pip install -r requirements.txt
pip freeze -r requirements.txt --exclude-editable > requirements.txt
```
What this achieves is that we explicitly list all the recursive dependencies in  `requirements.txt` deployed to PyPI, including `dataclasses`.

## Solution

I see no reason why we need to do that, thus removing this part of the deployment script.

Reviewed By: karthikprasad

Differential Revision: D25121368

fbshipit-source-id: c48f3b147cc10e11b5f9dadfe703bed2e6e00dd6